package com.restaurant.model.entities;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig veinDynamicDaoConfig;

    private final VeinDynamicDao veinDynamicDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        veinDynamicDaoConfig = daoConfigMap.get(VeinDynamicDao.class).clone();
        veinDynamicDaoConfig.initIdentityScope(type);

        veinDynamicDao = new VeinDynamicDao(veinDynamicDaoConfig, this);

        registerDao(VeinDynamic.class, veinDynamicDao);
    }
    
    public void clear() {
        veinDynamicDaoConfig.clearIdentityScope();
    }

    public VeinDynamicDao getVeinDynamicDao() {
        return veinDynamicDao;
    }

}
